### PR TITLE
Fix Cmd-Enter not working to send toot

### LINKED ISSUE #1333: Allow Cmd-Enter to send toot
Glitchsoc appears to have reimplemented the Ctrl-Enter chord for sending a toot from the Compose window. This works well in Windows and Linux systems. But on Mac OS X, *Cmd-Enter* is the default chord in vanilla Mastodon, and changing to Ctrl-Enter breaks workflow for anyone on an OS X system.† (If nothing else, on this keyboard, there is a right-Command but not a right-Control, which means I have to use both hands to play the chord.)

Please add support for using the Cmd-Enter chord as the primary send button in the Compose window.

† I may be the only one, given that this appears to be the first time this has come up!

### PR DESCRIPTION
**Pull request by ThibG**
Fixes #1333

### CODE REVIEW

File: app/javascript/flavours/glitch/features/compose/components/compose_form.js [hunk 1]
```diff
@@ -158,19 +158,12 @@ class ComposeForm extends ImmutablePureComponent {
...
-  //  When the escape key is released, we focus the UI.
-  handleKeyUp = ({ key, ctrlKey, keyCode, metaKey, altKey }) => {
-    if (key === 'Escape') {
-      document.querySelector('.ui').parentElement.focus();
-    }
-
-    //  We submit the status on control/meta + enter.
-    if (keyCode === 13 && (ctrlKey || metaKey)) {
+  handleKeyDown = (e) => {
+    if (e.keyCode === 13 && (e.ctrlKey || e.metaKey)) {
```
Comment (igalic) [inline app/javascript/flavours/glitch/features/compose/components/compose_form.js:162]: so it's been 20 years now and this is still how we check if someone's pressed enter
