### PR TITLE
Fix CharacterCounter in vanilla UI

### LINKED ISSUE #1881: Vanilla flavor displays NaN in place of remaining character count
### Steps to reproduce the problem

1. Switch to vanilla flavour
2. Compose a post

### Expected behaviour

Character counter should show remaining characters

### Actual behaviour

NaN

### Detailed description

The Mastodon web compose box, vanilla flavour, showing "NaN" in place of where the character count is supposed to be

It stays this way even when typing in something.

### Specifications

fc340c915477821ede0b9d65a5762cf41e4a3bec

### PR DESCRIPTION
**Pull request by prplecake**
Fixes #1881

### CODE REVIEW

File: app/javascript/mastodon/features/compose/components/compose_form.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ import ImmutablePureComponent from 'react-immutable-pure-component';
 import { length } from 'stringz';
 import { countableText } from '../util/counter';
 import Icon from 'mastodon/components/icon';
-import { maxChars } from '../../../initial_state';
+import { maxChars } from 'flavours/glitch/initial_state';
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/compose/components/compose_form.js:24]: We shouldn't mix flavours. I think the proper fix would rather be to add `maxChars` back to `app/javascript/mastodon/initial_state.js`

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: app/javascript/mastodon/features/compose/components/compose_form.js (hunk 1 above)
Comment (ClearlyClaire) [reply app/javascript/mastodon/features/compose/components/compose_form.js:24]: I can't find it either :|
but I believe it was in a merge commit

Only `maxChars` was used, so only `maxChars` matters.

**Review by ClearlyClaire — APPROVED** [review]
